### PR TITLE
[WIP] Add a check for the presence of "scripts"

### LINKED ISSUE #224: [BUG] Package cannot be noarch if scripts argument is used
**Describe the bug**

If a package has the `scripts` argument in _setup.py_ it cannot be [`noarch`](https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python). Currently, this is not taken into account by Grayskull.

**To Reproduce**
1. Create package

**Expected behavior**

`noarch: python` should not be included in the `build:` section.

**Outputs**
If applicable, add the output to help explain your problem.

One example is [`remove_dagmc_tags`](https://github.com/svalinn/remove_dagmc_tags) which has the following [_setup.py_](https://github.com/svalinn/remove_dagmc_tags/blob/c529c688959647faaebba0a932f96c0c10891f61/setup.py#L17)

```python
setuptools.setup(
    name="remove_dagmc_tags",
    version="0.0.5",
    author="DAGMC development team",
    description="A tool for selectively removing tags such as the graveyard from DAGMC h5m files.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/svalinn/remove_dagmc_tags",
    packages=setuptools.find_packages(),
    zip_safe=True,
    package_dir={"remove_dagmc_tags": "remove_dagmc_tags"},
    scripts=['remove_dagmc_tags/remove-dagmc-tags'],
    package_data={
        "remove_dagmc_tags": [
            "requirements.txt",
            "README.md",
            "LICENSE",
        ],
        "tests": [
            "dagmc.h5m"
        ]
    },
    install_requires=[
        "numpy"
    ],
    # pymoab is also required for this package but is not available via pip
    # install
    tests_require=["pytest-cov"],
)
```

The output here is

```yaml
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
```

**Environment:**
 - https://www.marcelotrevisani.com/grayskull

**Additional context**

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
Fixes #224

### CODE REVIEW

**Comment by ocefpaf** [comment]
@marcelotrevisani let's add @ForgottenProgramme to the team here so we don't need to approve the ci run for every PR.

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani let's add @ForgottenProgramme to the team here so we don't need to approve the ci run for every PR.

invite sent

**Comment by marcelotrevisani** [comment]
Hi @ForgottenProgramme , can we close this PR as it was addressed in the https://github.com/conda-incubator/grayskull/pull/238 ?

**Comment by ForgottenProgramme** [comment]
@marcelotrevisani , yes. Thanks for reminding. 
Let's please close this PR. :)

**Pull request closed without merging**
