### PR TITLE
Add support for local sdist

### LINKED ISSUE #272: [FEATURE] Add support to build recipe from local sdist
**Is your feature request related to a problem? Please describe.**
At work we have many pure python packages that we'd like to deploy with conda.
Having people add a conda recipe is an extra step and often seen as duplicate work. For most packages the recipe should be quite straightforward and needed information already available in the setup.py or setup.cfg file.

**Describe the solution you'd like**
I'd like to generate the conda recipe from the local sdist (or wheel?) and automatically build the conda package during CI.

**Additional context**
If there is interest, I can try to add this feature.
I was first thing about adding a `grayskull local` subcommand but that might introduce some backward incompatibility (I think it would make sense to move some options common to `pypi` and `local` to the main parser).
An alternative is to just pass local files as `pypi_packages`. This is similar to what was done to add GitHub support.

### PR DESCRIPTION
**Pull request by beenje**
Added support to create recipe from local sdist.
I noticed some keys like `summary` were sometimes missing when parsing setup.cfg.
I added parsing some keys from PKG-INFO using [pkginfo](https://pypi.org/project/pkginfo/).

Fix #272

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
Hi @beenje , sorry for my delay, my son was born last week and I didn't have much time to take a look on my notifications.

I will review it now, thanks a lot!

**Comment by marcelotrevisani** [comment]
We had just one failing test that needed adjustment. I already fixed it to speed up the process so we can integrate that soon :)

**Comment by marcelotrevisani** [comment]
LGTM! 🎉 🎉 🎉 🎉 
thanks for your contribution! :)

**Comment by beenje** [comment]
Thanks!
And congratulations for your son!🎉
No problem for the delay, I'm sure you have more important things to do 😀

**Comment by marcelotrevisani** [comment]
Thanks! :)

I already generated a new version and it should be on conda-forge in 30minutes or so

**Pull request merged**
