### PR TITLE
Add extra quirks

### PR DESCRIPTION
**Pull request by BastianZim**
- fastjsonschema
- flair

### CODE REVIEW

**Comment by BastianZim** [comment]
Just to add:

```yaml
Boruta:
  conda_forge: boruta_py
  import_name: boruta
Flask-Cors:
  conda_forge: flask_cors
  import_name: flask_cors
Flask-JSON:
  conda_forge: flask_json
  import_name: flask_json
SoundFile:
  conda_forge: pysoundfile
  import_name: soundfile
```

was added at some point but not alphabetically. 
If that's important, I can just quickly sort this and add it to the PR.

**Comment by marcelotrevisani** [comment]
That is fine, no worries! 

I will approve this and merge it
Thanks for your contribution! :)

**Review by marcelotrevisani — APPROVED** [review]

**Comment by BastianZim** [comment]
Ok perfect, thanks for merging! :)

**Comment by marcelotrevisani** [comment]
I generated the version ``0.8.5`` with this modification.

You should be able to use it in one hour more or less on conda-forge.
https://github.com/conda-forge/grayskull-feedstock/pull/38

It is already o ``pypi`` as well:
https://pypi.org/project/grayskull/#description

**Comment by BastianZim** [comment]
Thank you!

**Pull request merged**
