### PR TITLE
Fix "compatible release" operator

### PR DESCRIPTION
**Pull request by maresb**
According to https://github.com/conda-incubator/grayskull/issues/348#issuecomment-1210348234, the currently-merged solution will break back-compatibility. Let's implement another solution instead.

(Hopefully I can take care of it this evening.)

### CODE REVIEW

**Comment by maresb** [comment]
I want to write code which is as reasonably correct and robust as practical. According to the [Conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#predictable-version-ordering), `dev`<`a`:
image

And also the `packaging` package agrees:
```python
>>> from packaging.version import Version
>>> a = Version("1.0.0a0")
>>> dev = Version("1.0.0dev0")
>>> dev<a
True
>>> a<dev
False
```

Thus I'm replacing `a` with `dev`. Any objections?

**Comment by marcelotrevisani** [comment]
that is perfect to me

**Comment by marcelotrevisani** [comment]
thanks for your contribution again! :tada: :tada: :tada:

**Comment by maresb** [comment]
Thanks so much for seeing this through with me!!! :smile:

**Pull request merged**
