### PR TITLE
Change license binding

### LINKED ISSUE #418: [BUG] grayskull separates multiple licenses with `&` rather than `AND`
**Describe the bug**

**To Reproduce**
`grayskull pypi marshmallow`
resulting `marshmallow/meta.yaml` has a line `  license: MIT & BSD-3-Clause` that produces:
```
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (recipe) and found it was in an excellent condition.

I do have some suggestions for making it better though...

For recipe:

License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).
```
from conda-forge's linter.

See: https://github.com/conda-forge/marshmallow-feedstock/pull/64

**Expected behavior**
`  license: MIT AND BSD-3-Clause`, which makes conda-forge's linter happy:
```
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (recipe) and found it was in an excellent condition.
```

See also: https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions

**Environment:**
 - `grayskull --version`: 1.8.4

### PR DESCRIPTION
**Pull request by BastianZim**
Closes #418

### CODE REVIEW

**Comment by BastianZim** [comment]
Not sure why the tests are failing. I don't think this is connected to this PR.

**Comment by marcelotrevisani** [comment]
Sorry, I was on holidays and I didn't check anything during that time, I am back now :)

**Comment by marcelotrevisani** [comment]
let me take a look at why the tests are failing, the PR looks good to me

**Comment by marcelotrevisani** [comment]
ok, found the problem
gonna fix in this PR if you dont mind

**Review by marcelotrevisani — APPROVED** [review]

**Comment by marcelotrevisani** [comment]
it should be fine now

**Comment by BastianZim** [comment]
No worries, thank you! :)

**Comment by BastianZim** [comment]
Hmm, seems like a GitHub error.

**Review by marcelotrevisani — APPROVED** [review]

**Pull request merged**
