### PR TITLE
[WIP]cran support

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Initial CRAN support based on @ForgottenProgramme PR (https://github.com/conda-incubator/grayskull/pull/349)

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
simple example for ``future 1.26.1``

```yaml
{% set name = "future" %}
{% set version = "1.26.1" %}

package:
  name: r-{{ name }}
  version: '{{ version }}'

source:
  url: https://cran.r-project.org/src/contrib/Archive/future/future_{{ version }}.tar.gz
  sha256: a35c0bdae86265ebe86119231802b6fbf7b1d533b57cb423d8483fbe779390d5

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-digest
    - r-globals >=0.15.0
    - r-listenv >=0.8.0
    - r-parallel
    - r-parallelly >=1.30.0
    - r-tools
    - r-utils
  run:
    - r-base
    - r-digest
    - r-globals >=0.15.0
    - r-listenv >=0.8.0
    - r-parallel
    - r-parallelly >=1.30.0
    - r-tools
    - r-utils

test:
  commands:
    - $R -e "library('future')"  # [not win]
    - "\"%R%\" -e \"library('future')\""  # [win]

about:
  home: https://future.futureverse.org, https://github.com/HenrikBengtsson/future
  summary: The purpose of this package is to provide a lightweight and unified Future API for sequential and parallel processing of R expression via futures.  The simplest way to evaluate an expression in parallel is to use `x %<-% { expression }` with `plan(multisession)`. This package implements sequential, multicore, multisession, and cluster futures.  With these, R expressions can be evaluated on the local machine, in parallel a set of local machines, or distributed on a mix of local and remote machines. Extensions to this package implement additional backends for processing futures via compute
    cluster schedulers, etc. Because of its unified API, there is no need to modify any code in order switch from sequential on the local machine to, say, distributed processing on a remote compute cluster. Another strength of this package is that global variables and functions are automatically identified and exported as needed, making it straightforward to tweak existing code to make use of futures.
  license: LGPL-2.1-or-later
```

**Comment by ocefpaf** [comment]
@mbargull, and anyone from the bioconda team, we would your input here.

**Comment by isuruf** [comment]
Why use a less featureful version of conda skeleton cran here? This has multiple issues
- No license_file file
- R_ARGS variable is not used
- cross-r-base is not added for non compiler recipes
- noarch: generic is not used
- DISABLE_AUTOBREW is not added

**Comment by isuruf** [comment]
Also, this PR vendors conda-build code and fails to distribute the license

**Comment by marcelotrevisani** [comment]
if you are keen to help to improve that part related to R, we are more than welcome to accept contributions or to open separated issues for it. Thanks!

**Comment by isuruf** [comment]
> Every Software starts with less features and increase in complexity with time.

Not all of the features I mentioned are necessary, but generating recipes that have incomplete licensing information is asking for trouble.

> The question here is why grayskull instead of conda-build. I guess that b/c the main reason is why we did this for Python recipes. The slow pace of conda-build development and the difficulty to get PRs accepted drove us to create a new recipe generator.

I don't question that. Moving skeletons out of conda-build is good.

From a look at the code here most of the code here is an almost identical copy of the conda-build code. https://github.com/conda-incubator/grayskull/blob/main/grayskull/strategy/cran.py#L61-L252
And then https://github.com/conda-incubator/grayskull/blob/d17444d66ebf50fdb5d97948c7ecfc654b0f68fa/grayskull/strategy/cran.py#L255-L346 seems like a stripped down version of the conda-build code.

I'm just curious why this is a stripped down version and not all features were not copied.

**Pull request merged**
