### PR TITLE
Add several packages to quirks

### PR DESCRIPTION
**Pull request by xylar**
This merge adds `asana`, `kubernetes`, `neo4j`, `redis`, and `trino` to the `config.yaml` file that maps between PyPi, conda-forge, and import names.

### CODE REVIEW

**Comment by xylar** [comment]
@BastianZim asked me to add `asana`.  The others are packages I had been renaming myself as part of an automated workflow to maintain the `apache-airflow-provider-*` packages but it will be wonderful to have Grayskull take care of this!

**Comment by marcelotrevisani** [comment]
Cool! Thanks for adding this! :)

**Review by marcelotrevisani — APPROVED** [review]

**Comment by xylar** [comment]
Now that I know about this feature, I will keep an eye out for others and add them as I see them.

**Comment by marcelotrevisani** [comment]
> Now that I know about this feature, I will keep an eye out for others and add them as I see them.

Nice! Thanks for that!

**Comment by xylar** [comment]
Thanks @marcelotrevisani!  And thanks for your work on Grayskull in general.  It's an amazingly helpful tool.

**Comment by marcelotrevisani** [comment]
> Thanks @marcelotrevisani! And thanks for your work on Grayskull in general. It's an amazingly helpful tool.

I am glad that is helping you :)

**Pull request merged**
