### PR TITLE
Create Documentation for Grayskull

### LINKED ISSUE #22: Create docs
- [ ] Create Wiki
- [ ] Create Docs
- [ ] Update README

### PR DESCRIPTION
**Pull request by ForgottenProgramme**
I used Sphinx to create the initial documentation for Grayskull. 
I used the "furo" theme. Feel free to suggest another theme. 
For now, I have created two sections: user guide and developer guide. 
Since Grayskull is actively under development, I thought it might be a good idea to have some developer-oriented documentation as well. 

Fixes #22

### CODE REVIEW

**Comment by ForgottenProgramme** [comment]
image

**Comment by ForgottenProgramme** [comment]
image

**Comment by ForgottenProgramme** [comment]
image

**Comment by marcelotrevisani** [comment]
awesome! 🎉 🎉 🎉 🎉 🎉  🚀 🚀 🚀 🚀 
Just one thing, can you modify the `pre-commit-config.yaml` to not run when someone changes the docs please?
```
exclude: docs
```
at the beginning of the file should do the job

**Comment by marcelotrevisani** [comment]
please let me know when you are ready to merge that so we can integrate it :)

**Comment by ForgottenProgramme** [comment]
@marcelotrevisani , Thankyou. :))
I think the initial setup for the documentation is fine for now. We will of course keep writing more and improving it. 
But we need to decide how we're going to host this documentation. 
I found this:
https://www.sphinx-doc.org/en/master/tutorial/deploying.html#publishing-your-html-documentation

**Comment by marcelotrevisani** [comment]
yes, we need to do this as well, that would be perfect! are you willing to add the CI part as well?

are you happy with your modification? can I merge it?

**Pull request merged**
