### PR TITLE
Fix issue 382

### LINKED ISSUE #382: [BUG] requirements needed with outputs
Conda forge fails with the message `'PYTHON' is undefined` when the `outputs` section is defined (i.e. extra requires).

The reason is this

```yaml
outputs:
  - name: pypushflow
    requirements:
      host: &id001
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host: *id001
      run:
        - pypushflow =={{ version }}
        - pymongo >=4
```

which should become

```yaml
requirements: # !!!!
  host:
    - python >=3.6
    - pip

outputs:
  - name: pypushflow
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6  # !!!!!
        - pypushflow =={{ version }}
        - pymongo >=4
```

Command:

```
grayskull pypi pypushflow --extras-require-all --extras-require-split --extras-require-test test --extras-require-exclude dev --strict-conda-forge
```

### PR DESCRIPTION
**Pull request by woutdenolf**
Closes #382

### CODE REVIEW

**Comment by woutdenolf** [comment]
I'm a bit struggling to understand the global and outputs `requirements` sections. For example when I do this

```yaml
requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

outputs:
  - name: pypushflow
    requirements:
      host: &id001
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host: *id001
      run:
        - python >=3.6
        - pypushflow =={{ version }}
        - pymongo >=4
```

I get a package with

```
pypushflow-mx 0.3.0 py310ha770c72_2
-----------------------------------
file name   : pypushflow-mx-0.3.0-py310ha770c72_2.tar.bz2
name        : pypushflow-mx
version     : 0.3.0
build       : py310ha770c72_2
build number: 2
size        : 5 KB
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/pypushflow-mx-0.3.0-py310ha770c72_2.tar.bz2
md5         : f817fc530992fb2458eb3fe3ba1966b0
timestamp   : 2022-08-31 11:54:36 UTC
dependencies: 
  - pymongo >=4
  - pypushflow 0.3.0
  - python >=3.10,<3.11.0a0
  - python_abi 3.10.* *_cp310
```

**Comment by marcelotrevisani** [comment]
> I'm a bit struggling to understand the global and outputs `requirements` sections. For example when I do this
> 
> ```yaml
> requirements:
>   host:
>     - python >=3.6
>     - pip
>   run:
>     - python >=3.6
> 
> outputs:
>   - name: pypushflow
>     requirements:
>       host: &id001
>         - python >=3.6
>         - pip
>       run:
>         - python >=3.6
>   - name: pypushflow-mx
>     requirements:
>       host: *id001
>       run:
>         - python >=3.6
>         - pypushflow =={{ version }}
>         - pymongo >=4
> ```
> 
> I get a package with
> 
> ```
> pypushflow-mx 0.3.0 py310ha770c72_2
> -----------------------------------
> file name   : pypushflow-mx-0.3.0-py310ha770c72_2.tar.bz2
> name        : pypushflow-mx
> version     : 0.3.0
> build       : py310ha770c72_2
> build number: 2
> size        : 5 KB
> license     : MIT
> subdir      : linux-64
> url         : https://conda.anaconda.org/conda-forge/linux-64/pypushflow-mx-0.3.0-py310ha770c72_2.tar.bz2
> md5         : f817fc530992fb2458eb3fe3ba1966b0
> timestamp   : 2022-08-31 11:54:36 UTC
> dependencies: 
>   - pymongo >=4
>   - pypushflow 0.3.0
>   - python >=3.10,<3.11.0a0   !!!!!!!!!!!!!!
>   - python_abi 3.10.* *_cp310   !!!!!!!!!!!!!!
> ```
> 
> @marcelotrevisani Any idea how this is supposed to work?

did you specify ``noarch: python``? if you don't , that is correct

**Comment by marcelotrevisani** [comment]
because if it is not ``noarch`` it will build the package for a specific python version, in this case conda build got python 3.10, if you want another version you can do ``conda build --python=3.9`` or something like that.

**Comment by woutdenolf** [comment]
Yes, I have `noarch: python` but is still makes `py310` packages.

Here is the full recipe generated by this MR:

https://github.com/conda-forge/pypushflow-feedstock/blob/main/recipe/meta.yaml

**Comment by marcelotrevisani** [comment]
> Yes, I have `noarch: python` but it still builds `py310*` conda packages.
> 
> Here is the full recipe generated by this MR:
> 
> https://github.com/conda-forge/pypushflow-feedstock/blob/main/recipe/meta.yaml
you also need to specify in the ``outputs``, like:
https://github.com/conda-forge/grayskull-feedstock/blob/4bff809d9de25fc87b503ec72cb7d8af14736a4d/recipe/meta.yaml#L26

**Comment by woutdenolf** [comment]
> you also need to specify in the outputs, like:

Oef. Then what about all the other `build` options like `entry_points`?

**Comment by marcelotrevisani** [comment]
> > you also need to specify in the outputs, like:
> 
> Oef. Then what about all the other `build` options like `entry_points`?

if you want that specific output to have it, you need to specify as well

**Comment by marcelotrevisani** [comment]
for a more complex example, please see this
https://github.com/conda-forge/tensorflow-feedstock/blob/main/recipe/meta.yaml

**Comment by woutdenolf** [comment]
> for a more complex example, please see this https://github.com/conda-forge/tensorflow-feedstock/blob/main/recipe/meta.yaml

Doesn't this mean that `grayskull` needs to copy the entire `build` section to the outputs?

**Comment by marcelotrevisani** [comment]
> > for a more complex example, please see this https://github.com/conda-forge/tensorflow-feedstock/blob/main/recipe/meta.yaml
> 
> Doesn't this mean that `grayskull` needs to copy the entire `build` section to each output?

that is a difficult question to answer, because that is not exact, the user should know which package should hold the entrypoints and such. But the ``noarch: python`` definitely should be set for all in the case that it can be a noarch package. But as we are just splitting the dependencies and creating multiple packages but with variations of the dependencies I believe we can just copy that, indeed.

**Comment by woutdenolf** [comment]
> > > for a more complex example, please see this https://github.com/conda-forge/tensorflow-feedstock/blob/main/recipe/meta.yaml
> > 
> > 
> > Doesn't this mean that `grayskull` needs to copy the entire `build` section to each output?
> 
> that is a difficult question to answer, because that is not exact, the user should know which package should hold the entrypoints and such. But the `noarch: python` definitely should be set for all in the case that it can be a noarch package. But as we are just splitting the dependencies and creating multiple packages but with variations of the dependencies I believe we can just copy that, indeed.

Indeed not straightforward. One could also say for example that `entry_points` only needs to be added to the base output as all other outputs depend on it. Anyway, that's for another MR. This one is ready for review.

**Review by marcelotrevisani — APPROVED** [review]
Cool! Thanks for your contribution! :)

**Pull request merged**
